init:
  variables:
    RAKUDO_VERSION: 75fa35e40f2a624ec67781dea81476b9077ab374
    SP6_LOG_NO_TIMESTAMPS: 1
    SP6_DUMP_TASK_CODE: 1

  packages:
    rakudo:
      version: $RAKUDO_VERSION

  script: |

    sudo apk add tree coreutils py3-ansi2html
    zef install https://github.com/melezhik/Sparrow6.git --force-install
    zef install --/test Tomty

main:
  build:
    pre: |
      export RAKUBIN=/tmp/whateverable/rakudo-moar/$RAKUDO_VERSION/bin/raku
      tomty  --all --show-failed --color | ansi2html
