init:
  variables:
    RAKUDO_VERSION: dd7f3eb976efeaee92d2678af642893cb1e51c60

  packages:
    rakudo:
      version: $RAKUDO_VERSION
main:
  build:
    pre: |
      set -x
      export RAKUBIN=/tmp/whateverable/rakudo-moar/$RAKUDO_VERSION/bin/raku
      zef install --/test Tomty
      tomty  --all --show-failed
