init:
  variables:
    RAKUDO_VERSION: bb944723705e5727b3de95b383056ec2fc9e77f8
    RAKUBIN: /tmp/whateverable/rakudo-moar/bb944723705e5727b3de95b383056ec2fc9e77f8/bin/raku

  packages:
    rakudo:
      version: $RAKUDO_VERSION
main:
  build:
    pre: |
      set -x
      zef install --/test Tomty
      tomty  --all --show-failed
