init:
  variables:
    RAKUDO_VERSION: 621d69e0e265c8d09dfd9239ef7cf506adf8046b
    SP6_LOG_NO_TIMESTAMPS: 1

  packages:
    rakudo:
      version: $RAKUDO_VERSION

  script: |
    sudo apk add tree coreutils
    zef install --/test Tomty 2>&1 
    
main:
  build:
    pre: |
      export RAKUBIN=/tmp/whateverable/rakudo-moar/$RAKUDO_VERSION/bin/raku
      tomty  --all --show-failed
