init:
  variables:
    SP6_LOG_NO_TIMESTAMPS: 1

  packages:
    rakudo: {}

  script: |
    set -e
    sudo apk add tree coreutils

main:
  build:
    pre: |
      set -e
      export SP6_DUMP_TASK_CODE=1
      tomty  --all --show-failed --color
