init:
  variables:
    RAKUDO_VERSION: 14fb6a5c3d4e4a747acc8b80df6f3cbb6061b2a6
    SP6_LOG_NO_TIMESTAMPS: 1

  packages:
    rakudo:
      version: $RAKUDO_VERSION

  script: |
    sudo apk add tree coreutils
    
main:
  build:
    pre: |
      set -x
      export RAKUBIN=/tmp/whateverable/rakudo-moar/$RAKUDO_VERSION/bin/raku
      zef install --/test Tomty
      tomty  --all --show-failed
