init:
  variables:
    RAKUDO_VERSION: 934f9895e93313da8ccdd24b1437ad35293ac6ef
    SP6_LOG_NO_TIMESTAMPS: 1

  packages:
    rakudo:
      version: $RAKUDO_VERSION

  script: |
    sudo apk add tree coreutils
    
main:
  build:
    pre: |
      set -x
      export RAKUBIN=/tmp/whateverable/rakudo-moar/$RAKUDO_VERSION/bin/raku
      zef install --/test Tomty
      tomty  --all --show-failed
