init:
  variables:
    RAKUDO_VERSION: dd7f3eb976efeaee92d2678af642893cb1e51c60
    RAKUBIN: /tmp/whateverable/rakudo-moar/dd7f3eb976efeaee92d2678af642893cb1e51c60/bin/raku

  packages:
    rakudo:
      version: $RAKUDO_VERSION
main:
  build:
    pre: |
      set -x
      zef install --/test Tomty
      tomty  --all --show-failed
