init:
  variables:
    RAKUDO_VERSION: f2546b446ca38a6eafc8b78d30a358f97c35402b
    RAKUBIN: /tmp/whateverable/rakudo-moar/f2546b446ca38a6eafc8b78d30a358f97c35402b/bin/raku
    SP6_LOG_NO_TIMESTAMPS: 1

  packages:
    rakudo:
      version: $RAKUDO_VERSION

  script: |
    sudo apk add tree coreutils
    
main:
  build:
    pre: |
      set -x
      zef install --/test Tomty
      tomty  --all --show-failed
