init:
  variables:
    RAKUDO_VERSION: 7e300e615e329e5d6755029808d053cd304614c4
    SP6_LOG_NO_TIMESTAMPS: 1

  packages:
    rakudo:
      version: $RAKUDO_VERSION

  script: |
    sudo apk add tree coreutils
    
main:
  build:
    pre: |
      set -x
      export RAKUBIN=/tmp/whateverable/rakudo-moar/$RAKUDO_VERSION/bin/raku
      zef install --/test Tomty
      tomty  --all --show-failed
